### ISSUE TITLE
C2679 Error while compiling "os << static_cast<int32_t>"

### ISSUE THREAD

**Issue by KLOSTERS** [freeman40/HazelDash#1]
MouseCodes.h
os << static_cast<int32_t>(mouseCode);

KeyCodes.h
os << static_cast<int32_t>(KeyCode);

produces C2679 Error while compiling

MSVC Configuration

Microsoft Visual Studio Community 2019
Version 16.6.2
VisualStudio.16.Release/16.6.2+30204.135
Microsoft .NET Framework
Version 4.8.03752

Installierte Version: Community

Visual C++ 2019   00435-60000-00000-AA049
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.6.948.25768
ASP.NET and Web Tools 2019

C#-Tools   3.6.0-4.20251.5+910223b64f108fcf039012e0849befb46ace6e66
C#-Komponenten, die in der IDE verwendet werden. Abhängig von Ihrem Projekttyp und den zugehörigen Einstellungen kann eine andere Version des Compilers verwendet werden.

IntelliCode-Erweiterung   1.0
Detaillierte Informationen zur IntelliCode Visual Studio-Erweiterung

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++-Assistenten   1.0
Microsoft Visual C++-Assistenten

NuGet-Paket-Manager   5.6.0
NuGet-Paket-Manager in Visual Studio. Weitere Informationen zu NuGet finden Sie unter https://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Testadapter für Google Test   1.0
Ermöglicht die Verwendung von Visual Studio-Testtools mit Komponententests, die für Google Test geschrieben wurden. Die Nutzungsbedingungen und Drittanbieterhinweise stehen im Installationsverzeichnis der Erweiterung zur Verfügung.

VC-Paket für Microsoft Visual Studio   1.0
VC-Paket für Microsoft Visual Studio

Visual Basic-Tools   3.6.0-4.20251.5+910223b64f108fcf039012e0849befb46ace6e66
Visual Basic-Komponenten, die in der IDE verwendet werden. Abhängig von Ihrem Projekttyp und den zugehörigen Einstellungen kann eine andere Version des Compilers verwendet werden.

Visual Studio-Tools für CMake   1.0
Visual Studio-Tools für CMake

Visual Studio Code-Debugadapter-Hostpaket   1.0
Interopebene zum Hosten der Visual Studio Code-Adapter in Visual Studio

**Comment by KLOSTERS** [comment]
changing 
MouseCodes.h
os << static_cast<int32_t>(mouseCode);
KeyCodes.h
os << static_cast<int32_t>(KeyCode);

to 

MouseCodes.h
os << static_cast<int>(mouseCode);
KeyCodes.h
os << static_cast<int>(KeyCode);

fixes the Issue.

**Comment by KLOSTERS** [comment]
adding

#include < cstdint >
#include < iostream >
#include < typeinfo >

to the files did it

**Comment by 0xworks** [comment]
Thanks for reporting this.
I've taken a look and it is actually an issue with the Hazel library rather than the HazelDash sample application.

The issue is that "MouseCodes.h" and "KeyCodes.h" use std::ostream without #include'ing <iostream>.  I guess the assumption is that <iostream> is already included by Hazel's precompiled header.

However, clients of Hazel (such as HazelDash) do not bring in Hazel's precompiled header and so encounter the compile error observed in this ticket.

As @KLOSTERS says, the fix is to #include <iostream> in both MouseCodes.h and KeyCodes.h.   This fix should really be pushed to the Hazel repository (I might log a ticket there to do that)
